<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-14T23:54:42 IST" name="Suite" finished-at="2022-06-14T23:56:35 IST" duration-ms="113274">
    <groups>
    </groups>
    <test started-at="2022-06-14T23:54:42 IST" name="TestThree" finished-at="2022-06-14T23:56:15 IST" duration-ms="93446">
      <class name="com.yahoo.TestCases.TestThree">
        <test-method signature="testThree()[pri:0, instance:com.yahoo.TestCases.TestThree@4f5991f6]" started-at="2022-06-14T23:54:42 IST" name="testThree" finished-at="2022-06-14T23:56:15 IST" duration-ms="93316" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- com.yahoo.TestCases.TestThree -->
    </test> <!-- TestThree -->
    <test started-at="2022-06-14T23:54:42 IST" name="TestFour" finished-at="2022-06-14T23:56:20 IST" duration-ms="98327">
      <class name="com.yahoo.TestCases.ThestFour">
        <test-method signature="testFour()[pri:0, instance:com.yahoo.TestCases.ThestFour@327bcebd]" started-at="2022-06-14T23:54:42 IST" name="testFour" finished-at="2022-06-14T23:55:58 IST" duration-ms="76467" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.yahoo.TestCases.ThestFour.testFour(ThestFour.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:com.yahoo.TestCases.ThestFour@327bcebd]" started-at="2022-06-14T23:56:00 IST" name="closingBrowser" finished-at="2022-06-14T23:56:20 IST" duration-ms="20101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
      </class> <!-- com.yahoo.TestCases.ThestFour -->
    </test> <!-- TestFour -->
    <test started-at="2022-06-14T23:54:42 IST" name="TestTwo" finished-at="2022-06-14T23:56:23 IST" duration-ms="101347">
      <class name="com.yahoo.TestCases.TestTwo">
        <test-method signature="testTwo()[pri:0, instance:com.yahoo.TestCases.TestTwo@32c4e8b2]" started-at="2022-06-14T23:54:42 IST" name="testTwo" finished-at="2022-06-14T23:56:23 IST" duration-ms="101173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- com.yahoo.TestCases.TestTwo -->
    </test> <!-- TestTwo -->
    <test started-at="2022-06-14T23:54:42 IST" name="CreateAccount" finished-at="2022-06-14T23:56:35 IST" duration-ms="113274">
      <class name="com.yahoo.TestCases.CreateAccount">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:com.yahoo.TestCases.CreateAccount@c94fd30]" started-at="2022-06-14T23:54:42 IST" name="openApplication" finished-at="2022-06-14T23:56:18 IST" duration-ms="95636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="doCreateAccount()[pri:0, instance:com.yahoo.TestCases.CreateAccount@c94fd30]" started-at="2022-06-14T23:56:18 IST" name="doCreateAccount" finished-at="2022-06-14T23:56:31 IST" duration-ms="13291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doCreateAccount -->
        <test-method is-config="true" signature="closure()[pri:0, instance:com.yahoo.TestCases.CreateAccount@c94fd30]" started-at="2022-06-14T23:56:31 IST" name="closure" finished-at="2022-06-14T23:56:35 IST" duration-ms="4221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- com.yahoo.TestCases.CreateAccount -->
    </test> <!-- CreateAccount -->
  </suite> <!-- Suite -->
</testng-results>
